# Generated by Django 6.0.2 on 2026-02-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='score',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='total_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
