# Generated by Django 6.0.2 on 2026-02-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_gamesession_id_alter_leaderboard_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
