# Generated by Django 6.0.2 on 2026-02-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_leaderboard_rank_leaderboard_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='leaderboard',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
